In [1]:
import os
import csv
import pandas as pd

In [2]:
data = pd.read_csv('data/Local_Area_Unemployment_Statistics__LAUS_.csv')

In [3]:
print(data)

                Area_Type                           Area Name        Date  \
0                   State                          California  01/01/1976
1                   State                          California  01/01/1976
2                  County                  Los Angeles County  01/01/1976
3                  County                  Los Angeles County  01/01/1976
4       Metropolitan Area  Los Angeles-Long Beach-Glendale MD  01/01/1976
...                   ...                                 ...         ...
171145                MSA                   Yuba City, CA MSA  10/01/2020
171146                MSA                   Yuba City, CA MSA  11/01/2020
171147                MSA                   Yuba City, CA MSA  12/01/2020
171148                MSA                   Yuba City, CA MSA  01/01/2021
171149                MSA                   Yuba City, CA MSA  02/01/2021

        Year     Month Seasonally Adjusted (Y/N) Status (Preliminary / Final)  \
0       1976   January                         N                        Final
1       1976   January                         Y                        Final
2       1976   January                         N                        Final
3       1976   January                         Y                        Final
4       1976   January                         N                        Final
...      ...       ...                       ...                          ...
171145  2020   October                         Y                        Final
171146  2020  November                         Y                        Final
171147  2020  December                         Y                        Final
171148  2021   January                         Y                        Final
171149  2021  February                         Y                       Prelim

        Labor Force  Employment  Unemployment  Unemployment Rate
0           9672362     8668016       1004346               0.103
1           9774280     8875685        898595               0.092
2           3364151     3040058        324093               0.096
3           3381856     3081806        300050               0.089
4           3364151     3040058        324093               0.096
...             ...         ...           ...                 ...
171145        71002       63708          7294               0.103
171146        70063       63828          6235               0.089
171147        71241       63938          7303               0.103
171148        72887       66512          6375               0.087
171149        73086       66778          6308               0.086

[171150 rows x 11 columns]

In [4]:
data_yrs = data.loc[(data['Year'] >= 2011)]

In [5]:
print(data_yrs)

       Area_Type          Area Name        Date  Year     Month  \
2927       State         California  01/01/2011  2011   January
2928       State         California  01/01/2011  2011   January
2929      County     Alameda County  01/01/2011  2011   January
2930      County      Alpine County  01/01/2011  2011   January
2931      County      Amador County  01/01/2011  2011   January
...          ...                ...         ...   ...       ...
171145       MSA  Yuba City, CA MSA  10/01/2020  2020   October
171146       MSA  Yuba City, CA MSA  11/01/2020  2020  November
171147       MSA  Yuba City, CA MSA  12/01/2020  2020  December
171148       MSA  Yuba City, CA MSA  01/01/2021  2021   January
171149       MSA  Yuba City, CA MSA  02/01/2021  2021  February

       Seasonally Adjusted (Y/N) Status (Preliminary / Final)  Labor Force  \
2927                           N                        Final     18297100
2928                           Y                        Final     18363800
2929                           N                        Final       777000
2930                           N                        Final          740
2931                           N                        Final        15230
...                          ...                          ...          ...
171145                         Y                        Final        71002
171146                         Y                        Final        70063
171147                         Y                        Final        71241
171148                         Y                        Final        72887
171149                         Y                       Prelim        73086

        Employment  Unemployment  Unemployment Rate
2927      15968200       2328900               0.127
2928      16113400       2250400               0.123
2929        691600         85400               0.110
2930           670            70               0.094
2931         12890          2340               0.153
...            ...           ...                 ...
171145       63708          7294               0.103
171146       63828          6235               0.089
171147       63938          7303               0.103
171148       66512          6375               0.087
171149       66778          6308               0.086

[128466 rows x 11 columns]

In [6]:
data_adjust = data_yrs.loc[(data_yrs['Seasonally Adjusted (Y/N)'] == 'N')]

In [7]:
print(data_adjust)

               Area_Type          Area Name        Date  Year     Month  \
2927               State         California  01/01/2011  2011   January
2929              County     Alameda County  01/01/2011  2011   January
2930              County      Alpine County  01/01/2011  2011   January
2931              County      Amador County  01/01/2011  2011   January
2932              County       Butte County  01/01/2011  2011   January
...                  ...                ...         ...   ...       ...
159925  Sub-County Place    Yountville town  12/01/2020  2020  December
159926  Sub-County Place         Yreka city  12/01/2020  2020  December
159927  Sub-County Place     Yuba City city  12/01/2020  2020  December
159928  Sub-County Place       Yucaipa city  12/01/2020  2020  December
159929  Sub-County Place  Yucca Valley town  12/01/2020  2020  December

       Seasonally Adjusted (Y/N) Status (Preliminary / Final)  Labor Force  \
2927                           N                        Final     18297100
2929                           N                        Final       777000
2930                           N                        Final          740
2931                           N                        Final        15230
2932                           N                        Final       100700
...                          ...                          ...          ...
159925                         N                  Preliminary         1000
159926                         N                  Preliminary         2950
159927                         N                  Preliminary        30400
159928                         N                  Preliminary        25200
159929                         N                  Preliminary         9200

        Employment  Unemployment  Unemployment Rate
2927      15968200       2328900               0.127
2929        691600         85400               0.110
2930           670            70               0.094
2931         12890          2340               0.153
2932         85200         15500               0.154
...            ...           ...                 ...
159925         900           100               0.092
159926        2700           250               0.083
159927       27300          3100               0.101
159928       23500          1700               0.068
159929        8000          1200               0.134

[124440 rows x 11 columns]

In [8]:
data_status = data_adjust.loc[(data_adjust['Status (Preliminary / Final)'] =="Final")]

In [9]:
print(data_status)

               Area_Type          Area Name        Date  Year     Month  \
2927               State         California  01/01/2011  2011   January
2929              County     Alameda County  01/01/2011  2011   January
2930              County      Alpine County  01/01/2011  2011   January
2931              County      Amador County  01/01/2011  2011   January
2932              County       Butte County  01/01/2011  2011   January
...                  ...                ...         ...   ...       ...
158902  Sub-County Place    Yountville town  12/01/2019  2019  December
158903  Sub-County Place         Yreka city  12/01/2019  2019  December
158904  Sub-County Place     Yuba City city  12/01/2019  2019  December
158905  Sub-County Place       Yucaipa city  12/01/2019  2019  December
158906  Sub-County Place  Yucca Valley town  12/01/2019  2019  December

       Seasonally Adjusted (Y/N) Status (Preliminary / Final)  Labor Force  \
2927                           N                        Final     18297100
2929                           N                        Final       777000
2930                           N                        Final          740
2931                           N                        Final        15230
2932                           N                        Final       100700
...                          ...                          ...          ...
158902                         N                        Final         1100
158903                         N                        Final         2960
158904                         N                        Final        31100
158905                         N                        Final        25600
158906                         N                        Final         9000

        Employment  Unemployment  Unemployment Rate
2927      15968200       2328900               0.127
2929        691600         85400               0.110
2930           670            70               0.094
2931         12890          2340               0.153
2932         85200         15500               0.154
...            ...           ...                 ...
158902        1000             0               0.038
158903        2780           180               0.060
158904       28600          2500               0.080
158905       24900           800               0.030
158906        8500           500               0.055

[111180 rows x 11 columns]

In [12]:
grouped_data= data_status.groupby(['Year','Area_Type'])

In [13]:
data_df = grouped_data.sum()

In [14]:
data_df

                        Labor Force  Employment  Unemployment  \
Year Area_Type
2011 County               220882330   194648410      26234750
     Metropolitan Area    216296700   190677400      25619200
     State                220881100   194647400      26234000
     Sub-County Place     203216260   179198290      24013610
2012 County               221817620   198492670      23327170
     Metropolitan Area    217307400   194530900      22777500
     State                221818800   198492500      23326100
     Sub-County Place     203973320   182634380      21326180
2013 County               222785860   202655560      20129510
     Metropolitan Area    218340300   198665900      19674600
     State                222784800   202654300      20130500
     Sub-County Place     205295460   186836620      18458620
2014 County               224120260   207175240      16946960
     Metropolitan Area    219714300   203143600      16570900
     State                224120300   207174300      16946100
     Sub-County Place     206303600   190756370      15536670
2015 County               225890280   211768850      14121160
     Metropolitan Area    221490800   207679900      13810300
     State                225889600   211769000      14120900
     Sub-County Place     208004360   195051670      12946040
2016 County               228144690   215586260      12559970
     Metropolitan Area    223753400   211475500      12279200
     State                228144200   215584900      12559400
     Sub-County Place     209730540   198422590      11292100
2017 County               230086160   218961880      11123890
     Metropolitan Area    225695500   214814000      10881000
     State                230085400   218961900      11123600
     Sub-County Place     212086220   202026470      10040050
2018 County               231167430   221308810       9858490
     Metropolitan Area    226788100   217144000       9645000
     State                231166800   221309000       9857900
     Sub-County Place     213153490   204240360       8905690
2019 County               232244420   222606150       9638490
     Metropolitan Area    227881500   218451000       9430000
     State                232245000   222606400       9638600
     Sub-County Place     214249730   205536650       8703710
2021 County                18622130    16901490       1720250
     Metropolitan Area     18273100    16581600       1691400
     State                 18621900    16901700       1720200
     Sub-County Place      17197610    15598930       1599290

                        Unemployment Rate
Year Area_Type
2011 County                         95.134
     Metropolitan Area              47.019
     State                           1.427
     Sub-County Place             1443.973
2012 County                         85.948
     Metropolitan Area              42.166
     State                           1.262
     Sub-County Place             1316.487
2013 County                         73.409
     Metropolitan Area              36.334
     State                           1.084
     Sub-County Place             1148.821
2014 County                         62.205
     Metropolitan Area              31.237
     State                           0.907
     Sub-County Place             1010.406
2015 County                         52.818
     Metropolitan Area              27.042
     State                           0.752
     Sub-County Place              871.969
2016 County                         48.447
     Metropolitan Area              24.990
     State                           0.661
     Sub-County Place              789.793
2017 County                         42.438
     Metropolitan Area              21.813
     State                           0.579
     Sub-County Place              693.080
2018 County                         37.264
     Metropolitan Area              19.158
     State                           0.512
     Sub-County Place              617.741
2019 County                         36.560
     Metropolitan Area              18.977
     State                           0.498
     Sub-County Place              584.438
2021 County                          5.084
     Metropolitan Area               2.623
     State                           0.092
     Sub-County Place               89.317